### ISSUE TITLE
Something wrong with the factory_girl hack?

### ISSUE THREAD

**Issue by NobbZ** [locriani/magmawiki#8]
Since commit ab9bd1a09c9e0e96c3fc I get the following error when doing anything in test env!

I made my example snippet with a simple `rake db:migrate RAILS_ENV=test`

```
nmelzer@ubuntu-Delly:~/Dokumente/sources/ruby/1.8.7/rails30/magmawiki$ rake db:migrate --trace RAILS_ENV=test
rake aborted!
cannot remove Object::Factory
/home/nmelzer/Dokumente/sources/ruby/1.8.7/rails30/magmawiki/config/application.rb:12:in `remove_const'
/home/nmelzer/Dokumente/sources/ruby/1.8.7/rails30/magmawiki/config/application.rb:12:in `send'
/home/nmelzer/Dokumente/sources/ruby/1.8.7/rails30/magmawiki/config/application.rb:12
/home/nmelzer/.rvm/rubies/ruby-1.8.7-p352/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
/home/nmelzer/.rvm/rubies/ruby-1.8.7-p352/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
/home/nmelzer/Dokumente/sources/ruby/1.8.7/rails30/magmawiki/Rakefile:4
/home/nmelzer/.rvm/gems/ruby-1.8.7-p352@magmawiki/gems/rake-0.9.2/lib/rake/rake_module.rb:25:in `load'
/home/nmelzer/.rvm/gems/ruby-1.8.7-p352@magmawiki/gems/rake-0.9.2/lib/rake/rake_module.rb:25:in `load_rakefile'
/home/nmelzer/.rvm/gems/ruby-1.8.7-p352@magmawiki/gems/rake-0.9.2/lib/rake/application.rb:495:in `raw_load_rakefile'
/home/nmelzer/.rvm/gems/ruby-1.8.7-p352@magmawiki/gems/rake-0.9.2/lib/rake/application.rb:78:in `load_rakefile'
/home/nmelzer/.rvm/gems/ruby-1.8.7-p352@magmawiki/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/home/nmelzer/.rvm/gems/ruby-1.8.7-p352@magmawiki/gems/rake-0.9.2/lib/rake/application.rb:77:in `load_rakefile'
/home/nmelzer/.rvm/gems/ruby-1.8.7-p352@magmawiki/gems/rake-0.9.2/lib/rake/application.rb:61:in `run'
/home/nmelzer/.rvm/gems/ruby-1.8.7-p352@magmawiki/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/home/nmelzer/.rvm/gems/ruby-1.8.7-p352@magmawiki/gems/rake-0.9.2/lib/rake/application.rb:59:in `run'
/home/nmelzer/.rvm/gems/ruby-1.8.7-p352@magmawiki/gems/rake-0.9.2/bin/rake:32
/home/nmelzer/.rvm/gems/ruby-1.8.7-p352@magmawiki/bin/rake:19:in `load'
/home/nmelzer/.rvm/gems/ruby-1.8.7-p352@magmawiki/bin/rake:19
```

**Comment by epitron** [comment]
I couldn't figure out why the hack doesn't work in the test environment, so I just obeyed the API-breaking masters and changed everything to FactoryGirl.
